name: zattabi
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  uuid: ^3.0.4
  flutter_typeahead: ^3.1.1 # see if you use it anywhere
  beamer: ^0.11.2
  flutter_card_swipper: ^0.4.0
  image_picker: ^0.7.4   # Dosen't pick multiple images so I'm currently using multi_image_picker above
  get: ^4.1.3
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.3
  http: ^0.13.1
  firebase_auth: ^1.0.3
  flutter_spinkit: ^5.0.0
  email_validator: ^2.0.1
  shared_preferences: ^2.0.5 # I'M UNABLE TO MAKE THIS WORK
  geocode: ^1.0.1
  geolocator: ^7.0.3
  location: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/
  
